### ISSUE TITLE
How can I get response

### ISSUE THREAD

**Issue by carvendy** [plutov/paypal#102]
![image](https://user-images.githubusercontent.com/9424943/62449393-a3a82e00-b79c-11e9-9f24-ba32ec548f09.png)

![image](https://user-images.githubusercontent.com/9424943/62449433-c2a6c000-b79c-11e9-9d72-9df4df2ebb4c.png)

**Comment by plutov** [comment]
@carvendy you should send `&refundResult` as a pointer. So after execution `refundResult` var will be updated.

```
err := paypal.SendWithAuth(req, &refundResult)
```
