### ISSUE TITLE
Add Go modules

### ISSUE THREAD

**Issue by plutov** [plutov/paypal#108]

**Comment by roopakv** [comment]
This shouldbe fairly simple to do however we have to decide which approach we want to take for versioning, considering we are beyond 2.

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

@plutov thoughts on the way you think we should proceed

**Comment by plutov** [comment]
Yeah... It seems we'll need v3 which will support modules. We just need to make sure that this change won't break current imports.

**Comment by roopakv** [comment]
i sort of feel like it might be best to start a v3 and bump dependencies as described in the branch method. Since we have 0 depenedencies, we dont event need to move away from master.

wdyt

**Comment by plutov** [comment]
Agree, our `go.mod` will contain only the name of our module. Then let's bump it!

**Comment by plutov** [comment]
@roopakv thanks for the PR, I made small changes and merged the PR.

**Comment by roopakv** [comment]
woot thank you!
