### ISSUE TITLE
How can I use deprecated (v1) features with go module (github.com/plutov/paypal/v3)?

### ISSUE THREAD

**Issue by adriendomoison** [plutov/paypal#116]
I would like to use `/v1/payments/payment` in order to use the deprecated express checkout feature from PayPal (Except if I am missing something, there are no ways with v2 to create a fully custom button on the front-end, since they are really trying to force their slow/not customizable importable checkout button on every website now)

I understand I can use `go get github.com/plutov/paypal@v1.1.4` to use the old features but then I can't use go modules. Would it be possible to add go.mod support to this version too?

Thanks!

**Comment by roopakv** [comment]
Hey @adriendomoison sorry I missed this!

you should be able to use any API of paypal's which the module doesnt have support for by using the method in the [missing-endpoints](https://github.com/plutov/paypal#missing-endpoints) section of the readme. Please let us know if this doesnt work for you
