### ISSUE TITLE
how to get authID from `AuthorizeOrder`?????

### ISSUE THREAD

**Issue by elvis-hp** [plutov/paypal#122]

**Comment by roopakv** [comment]
sorry could you add more information about what is not working for you?

**Comment by siriele** [comment]
// AuthorizeOrder - https://developer.paypal.com/docs/api/orders/v2/#orders_authorize
// Endpoint: POST /v2/checkout/orders/ID/authorize
func (c *Client) AuthorizeOrder(orderID string, authorizeOrderRequest AuthorizeOrderRequest) (*Authorization, error) {
	auth := &Authorization{}

	req, err := c.NewRequest("POST", fmt.Sprintf("%s%s", c.APIBase, "/v2/checkout/orders/"+orderID+"/authorize"), authorizeOrderRequest)
	if err != nil {
		return auth, err
	}

	if err = c.SendWithAuth(req, auth); err != nil {
		return auth, err
	}

	return auth, nil
}

Authorization should be AuthorizationResponse

**Comment by elvis-hp** [comment]
ID of Authorization response is not auth_id, it still is order-id. I checked!
`
// Authorization struct
	Authorization struct {
		ID               string                `json:"id,omitempty"`
		CustomID         string                `json:"custom_id,omitempty"`
		InvoiceID        string                `json:"invoice_id,omitempty"`
		Status           string                `json:"status,omitempty"`
		StatusDetails    *CaptureStatusDetails `json:"status_details,omitempty"`
		Amount           *PurchaseUnitAmount   `json:"amount,omitempty"`
		SellerProtection *SellerProtection     `json:"seller_protection,omitempty"`
		CreateTime       *time.Time            `json:"create_time,omitempty"`
		UpdateTime       *time.Time            `json:"update_time,omitempty"`
		ExpirationTime   *time.Time            `json:"expiration_time,omitempty"`
	Links            []Link                `json:"links,omitempty"`

	}
`

**Comment by elvis-hp** [comment]
this is auth_id from api response from postmain, it is in purchase_units[0][payments] [authorizations][id] => 1AM86147H1957233G 
`
{
    "id": "65G59924MX475703V",
    "purchase_units": [
        {
            "reference_id": "default",
            "shipping": {
                "name": {
                    "full_name": "fsef sefsef"
                }
            },
            "payments": {
                "authorizations": [
                    {
                        "status": "CREATED",
                        "id": "1AM86147H1957233G",
                        "amount": {
                            "currency_code": "USD",
                            "value": "199.00"
                        },
                        "seller_protection": {
                            "status": "ELIGIBLE",
                            "dispute_categories": [
                                "ITEM_NOT_RECEIVED",
                                "UNAUTHORIZED_TRANSACTION"
                            ]
                        },
                        "expiration_time": "2019-11-08T17:02:00Z",
                        "links": [
                            {
                                "href": "https://api.sandbox.paypal.com/v2/payments/authorizations/1AM86147H1957233G",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v2/payments/authorizations/1AM86147H1957233G/capture",
                                "rel": "capture",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v2/payments/authorizations/1AM86147H1957233G/void",
                                "rel": "void",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v2/payments/authorizations/1AM86147H1957233G/reauthorize",
                                "rel": "reauthorize",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v2/checkout/orders/65G59924MX475703V",
                                "rel": "up",
                                "method": "GET"
                            }
                        ],
                        "create_time": "2019-10-10T17:02:00Z",
                        "update_time": "2019-10-10T17:02:00Z"
                    }
                ]
            }
        }
    ],
    "payer": {
        "name": {
            "given_name": "fsef",
            "surname": "sefsef"
        },
        "email_address": "fsese@fsef.gseg",
        "payer_id": "Y948H5QY8GTEW",
        "phone": {
            "phone_number": {
                "national_number": "12335235232"
            }
        },
        "address": {
            "country_code": "US"
        }
    },
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v2/checkout/orders/65G59924MX475703V",
            "rel": "self",
            "method": "GET"
        }
    ],
    "status": "COMPLETED"
}`

**Comment by siriele** [comment]
So the payments object is not exposed on the go struct.

**Comment by roopakv** [comment]
happy to take a PR. if not i can try look at it this weekend.

**Comment by siriele** [comment]
Essh. I'm up against a deadline, but I'll look today

**Comment by siriele** [comment]
Actually, I'm looking at the SDK and it's marked as go 1.12. I'm currently stuck on using go1.11. For now I will just work it and work off of that
