### ISSUE TITLE
Get information from Order after capture

### ISSUE THREAD

**Issue by chriskolenko** [plutov/paypal#125]
When getting and Order by ID after a Capture you receive the "Payments" object with all the captures. 
At the moment this property does not exist inside PurchaseUnit

My use case is as follows. 
After a capture has been made I would like to receive information from the order to find the amount paypal has charged me in fees. My current system design allows for failures, so if a Capture has already been taken it doesn't try again. Right now I think I'm stuck querying for this info via the Order API.

https://github.com/plutov/paypal/blob/a6e6c7ae9812772700571abfb3063615fceb59b2/types.go#L471-L474

Thoughts before I raise a PR?

**Comment by roopakv** [comment]
Yes we should have all objects mimic the response. Happy to review a PR feel free to send one my way.
