### ISSUE TITLE
Subscription API

### ISSUE THREAD

**Issue by AlessandroSechi** [plutov/paypal#133]
Hello, is it possible to make calls to Subscription API? I’m looking for a way to call something like

`GET https://api.paypal.com/v1/billing/subscriptions/SubId`

**Comment by roopakv** [comment]
yes, feel free to send a PR. I can do it, but it might take some time.

**Comment by AlessandroSechi** [comment]
Ok. I'll do it in the next days

**Comment by AlessandroSechi** [comment]
Ok. I added it. I used existing structures where possible, but I had to create some new ones
