### ISSUE TITLE
Consts for order status

### ISSUE THREAD

**Issue by LeafHacker** [plutov/paypal#136]
Currently you have [consts](https://github.com/plutov/paypal/blob/0e7098b/types.go#L57-L63) for order intent, however nothing for [status](https://developer.paypal.com/docs/api/orders/v2/#orders-get-response)

![image](https://user-images.githubusercontent.com/23565638/74084968-34bdd180-4a6c-11ea-8576-571a307f8e8f.png)

**Comment by plutov** [comment]
@LeafHacker can you please create a PR for this?
