### ISSUE TITLE
SendWithAuth getting new access token once expired?

### ISSUE THREAD

**Issue by novikk** [plutov/paypal#15]
I've seen that the description of the function says that it will get a new access token when the current one is about to expire, but I can't see to find this logic anywhere in the code. Is it already implemented?

https://github.com/logpacker/PayPal-Go-SDK/blob/master/client.go#L95

**Comment by plutov** [comment]
@novikk I've implemented it, please fetch new version

**Comment by novikk** [comment]
@plutov great, thanks!
