### ISSUE TITLE
Support commerce platform for marketplace

### ISSUE THREAD

**Issue by tyrong** [plutov/paypal#152]
Is there anyway to integrate with the paypal commerce platform for marketplaces?
https://developer.paypal.com/docs/platforms/

**Comment by roopakv** [comment]
Hi tyrong, as far as I know, a lot of the `platforms` code is front end code.

I know there are a few API calls they have but we haven't ported those to this lib yet. Feel free to open PRs otherwise, we can look into it as someone gets time.

**Comment by tyrong** [comment]
Thanks @roopakv ill close this off 👍
