### ISSUE TITLE
client.Client

### ISSUE THREAD

**Issue by nidzovito** [plutov/paypal#16]
I have error from this code.
client, err := paypalsdk.NewClient(secretKeys.PaypalSandboxClientId, secretKeys.PaypalSandboxSecret, paypalsdk.APIBaseSandBox)
    //  client, err := paypalsdk.NewClient(secretKeys.PaypalClientId, secretKeys.PaypalSecret, paypalsdk.APIBaseLive)
    if err != nil {
        panic(err)
    }

```
// this required making paypalsdk.Client.client PUBLIC
client.Client = urlfetch.Client(ctx)

if _, err := client.GetAccessToken(); err != nil {
    panic(err)
}
```

Error Msg:
client.Client undefined (type *paypalsdk.Client has no field or method Client, but does have paypalsdk.client)

**Comment by plutov** [comment]
Why do you need to have exportable Client? Actually, we can do it, but the name `Client.Client` is stupid, so let's think about another name of struct field.
