### ISSUE TITLE
Add payer information GetOrder to response

### ISSUE THREAD

**Issue by jalandis** [plutov/paypal#168]
From the [Paypal documentation](https://developer.paypal.com/docs/api/orders/v2/#orders-get-response), the get order request returns a payer object.  I see this data in the raw JSON response but it is currently discarded by the library.

It would be helpful if this information is returned with the `GetOrder` function.  Not sure if the `Order` type can be updated or if a new type is necessary.  This may be a breaking change request depending on that decision.

**Comment by plutov** [comment]
It seems like your PR is merged already. Thank you!
