### ISSUE TITLE
WebhookEvent.Resource and the Resource struct is confusing and maybe problematic

### ISSUE THREAD

**Issue by thomasf** [plutov/paypal#192]
There are many different types of webhook events with different resource types. I'm not even sure which kind of event the current struct that's just names Resource is supposed to represent.

I have just started digging into this put it would probably be best to exclude the resource field in the base type entirely or make it to a raw []byte json field or something.

This is how the WebhookEvent struct looks now which I think that the Resource field probably should be removed from. 
 
```go
	// WebhookEvent struct
	WebhookEvent struct {
		ID              string    `json:"id"`
		CreateTime      time.Time `json:"create_time"`
		ResourceType    string    `json:"resource_type"`
		EventType       string    `json:"event_type"`
		Summary         string    `json:"summary,omitempty"`
		Resource        Resource  `json:"resource"`
		Links           []Link    `json:"links"`
		EventVersion    string    `json:"event_version,omitempty"`
		ResourceVersion string    `json:"resource_version,omitempty"`
	}
```

The paypal API allows subscribing to different urls for different event types so ideally a consumer would probably set up one http handler per type so that parsing messages is as straight forward as possible.
 
Then an event per event type or per event type with a different resource can be formulated along the line of this:

```go
	PaymentPayoutsItemEvent struct {
		WebhookEvent
		Resource PayoutItem // or whatever type fits
	}
```

I am going to need at lest all types of payouts event types which at least means that I need support for 2 different resource types for my current project so I will have to make it work some how.

I am considering creating this as separate go module to this one. It can probably work and maybe it's better to not add many more types to the paypal package and keep them as separate entries. I guess I will find out if tighter integration is wanted or not as I progress.

**Comment by thomasf** [comment]
Something like this seems to be the way to go and I think that having a separate go module for it also makes sense so not to clutter the paypal package with it. I will move this to a public go module after I'm done with the implementation in my application. 

Maybe we can deprecate paypal.WebhookEvent struct after this and recommend people to use the new package for consuming webhooks instead. We'll see.

```go


type (
	Event struct {
		ID              string        `json:"id"`
		CreateTime      time.Time     `json:"create_time"`
		ResourceType    string        `json:"resource_type"`
		EventType       string        `json:"event_type"`
		Summary         string        `json:"summary,omitempty"`
		Links           []paypal.Link `json:"links"`
		EventVersion    string        `json:"event_version,omitempty"`
		ResourceVersion string        `json:"resource_version,omitempty"`
	}

	AnyEvent struct {
		Event
		Resource json.RawMessage `json:"resource"`
	}

	PaymentPayoutsItemEvent struct {
		Event
		Resource paypal.PayoutItemResponse `json:"resource"`
	}

	PaymentPayoutsBatchEvent struct {
		Event
		Resource paypal.PayoutResponse `json:"resource"`
	}
)
```

**Comment by plutov** [comment]
https://github.com/plutov/paypal/commit/52acc61786b55585df8f37b026d22bbb8dda820d

**Comment by thomasf** [comment]
Maybe we could opt for not including concrete event types like `PaymentPayoutsItemEvent` and  `PaymentPayoutsBatchEvent` structs in the package. 

Unless we add specific functionality tied to those they are mostly just noise.. 

It's probably better to write a little bit of documentation on the `Event` struct to instruct users to create their own sub classes using the other types in the package. Otherwise there are about 30 or so other event structs that could be added which is just even more noise.
