### ISSUE TITLE
Better Usage Examples

### ISSUE THREAD

**Issue by jonfairbanks** [plutov/paypal#197]
Better examples are needed on how to use this package beyond getting a simple access token. 

For example I am trying to simply list active subscriptions (`/v1/billing/plans`).

This works fine: 
```
accessToken, err := c.GetAccessToken(context.Background())
fmt.Println(accessToken)
```

This does not:
```
plans, err := c.ListBillingPlans(context.Background(), *paypal.BillingPlanListParams)
fmt.Println(plans)
```

How is this supposed to be used beyond the simple token use-case? I don't need any special parameters passed in this case. Just the defaults from [ListParams](https://pkg.go.dev/github.com/plutov/paypal/v4#ListParams).

**Comment by plutov** [comment]
Thanks for the feedback. Actually it was there before, so I added it back.

**Comment by plutov** [comment]
https://github.com/plutov/paypal/commit/1e23f8dd7d28b1e39d9878251ea0ea8e58ecb82b

**Comment by jonfairbanks** [comment]
Thank you for the quick fix. 💯
