### ISSUE TITLE
Random question about the library

### ISSUE THREAD

**Issue by yyewolf** [plutov/paypal#200]
I have a project in Golang and I'd like to know if by using this library it would be possible to set up a simple system that takes a monthly payment.
It would also executes a function when the payment is processed and another one if the user has stopped paying for it.

Would this be possible by using this library or not ?

**Comment by Kizz122** [comment]
> I have a project in Golang and I'd like to know if by using this library it would be possible to set up a simple system that takes a monthly payment.
> It would also executes a function when the payment is processed and another one if the user has stopped paying for it.
> 
> Would this be possible by using this library or not ?

**Comment by plutov** [comment]
Hi @yyewolf @Kizz122 yes, it is possible since Paypal can do that.
