### ISSUE TITLE
Please restore UserActionSubscribeNow

### ISSUE THREAD

**Issue by rsq424** [plutov/paypal#201]
Subscriptions
https://developer.paypal.com/docs/api/subscriptions/v1/#definition-application_context
need **CONTINUE** or **SUBSCRIBE_NOW**

Orders
https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context
need **CONTINUE** or **PAY_NOW**

**Comment by plutov** [comment]
@rsq424 can you please create a PR for that if you have time?

**Comment by plutov** [comment]
@rsq424 added
