### ISSUE TITLE
Identity - get access token

### ISSUE THREAD

**Issue by Raggaer** [plutov/paypal#21]
I am trying to get an access token after an user has logged in with paypal.

```
client, err := paypalsdk.NewClient(util.Config.PayPal.ClientID, util.Config.PayPal.Secret, paypalsdk.APIBaseSandBox)

if err != nil {
	log.Fatal(err)
}

client.SetLog(os.Stdout)

token, err := client.GrantNewAccessTokenFromAuthCode(req.URL.Query().Get("code"), "myURL")
```

However I am always getting this error: 

`{"error_description":"client id or secret is null","error":"invalid_client","correlation_id":"88feef2c749e8","information_link":"https://developer.paypal.com/docs/api/#errors"}`

My ClientID and Secret are correctly set. I can get an access token without any error using `client.GetAccessToken()`

What I am missing? Thanks

**Comment by plutov** [comment]
I have fixed it. Please try again, but be sure that you call `GetAccessToken` before `GrantNewAccessTokenFromAuthCode`
