### ISSUE TITLE
Suggestion: Mark all functions that represent deprecated paypal api resources as deprecated in godoc comment.

### ISSUE THREAD

**Issue by thomasf** [plutov/paypal#210]
A comment string`that looks something like this so they are clearly marked in godoc

```
// Deprecated: This API resource is deprecated by PayPal.
```

Just to make godoc clearer like this https://pkg.go.dev/github.com/plutov/paypal/v4#Resource

**Comment by sbshah97** [comment]
Hi is there something I can contribute to ?

**Comment by plutov** [comment]
@sbshah97 yes please review the code and add the annotations.
