### ISSUE TITLE
Get Order - Incomplete response object

### ISSUE THREAD

**Issue by DarioNevistic** [plutov/paypal#214]
According to the [documentation](https://developer.paypal.com/docs/api/orders/v2/#orders_get), returned struct from the endpoint `// Endpoint: GET /v2/checkout/orders/ID` is incomplete (`PurchaseUnit`, `Shipping Address`).

Please add missing fields (shipping info, also shipping address JSON keys are invalid - `line_1` instead of `address_line_1`, etc.), `CapturedPurchaseUnit` instead of `PurchaseUnit, etc.

**Comment by thomasf** [comment]
Why not add them yourself? it's probably the quickest way for you to get them added.

**Comment by thomasf** [comment]
The shipping address struct seems to be from the v1 api so make sure that there isn't any v1 api function using it because that one will break instead.

**Comment by thomasf** [comment]
There is a tendency of optimistic struct reuse for multiple api calls in this package that does not really work in reality and it's seldom even clear if a struct is a V1 or V2 paypal object.

**Comment by DarioNevistic** [comment]
Please check the [PR](https://github.com/plutov/paypal/pull/215).

**Comment by plutov** [comment]
Thank you for the PR @DarioNevistic
