### ISSUE TITLE
Bug in ReauthorizeAuthorization 

### ISSUE THREAD

**Issue by hogue40** [plutov/paypal#219]
At this line in ReauthorizeAuthorization:

https://github.com/plutov/paypal/blob/a5cff3c18c155671ef054f5e355e4530d45fdf18/authorization.go#L74

There seem to be a couple of typos in the request body's parameter names:

- `currency` should be changed to `currency_code`
- `total` should be changed to `value`

Per the API docs here:

https://developer.paypal.com/docs/api/payments/v2/#authorizations_reauthorize

**Comment by plutov** [comment]
Thanks for fixing it!
