### ISSUE TITLE
Make the mutex private in the structure

### ISSUE THREAD

**Issue by bartek1912** [plutov/paypal#228]
The mutex's methods are exposed - the client has public methods `Lock` and `Unlock`, which is kind of misleading - they're present in the autocomplete. It would be great to simply name the field like `mtx` (lowercase) to make it private.

https://github.com/plutov/paypal/blob/1a2c109908d6b7b98541396f175687c2d08ee263/types.go#L396

**Comment by sbshah97** [comment]
Is this still open ? I'd like to contribute?

**Comment by akshayDev17** [comment]
Hi , @bartek1912  can this be closed, since [this commit](https://github.com/plutov/paypal/commit/1bb626d559d803bc19f0932afad241a1f4f57f32) was approved and addresses this issue?
