### ISSUE TITLE
Suggestion: Error checking for malformed httpReq.Body on VerifyWebhookSignature

### ISSUE THREAD

**Issue by madprogramer** [plutov/paypal#230]
This is not necessarily a bug, but it has given me a lot of trouble personally, and will most likely give more people headaches in the future. When verifying Webhook events, event bodies should **NOT** be empty in the first place. The trouble is, sometimes you might end up consuming the `httpReq.Body` before calling `VerifyWebhookSignature`. In other words, passing an empty or partially read body. At this point, Go will produce a very verbose error message.

One option _might be_, to add a better error message, because there already is a `httpReq.Body != nil` checker. We still need to consider the partial-reading case, but this should be trivial. However, I would prefer allowing for `omitempty` in the json field, as well:

```go
type verifyWebhookSignatureRequest struct {
    AuthAlgo         string          `json:"auth_algo,omitempty"`
    CertURL          string          `json:"cert_url,omitempty"`
    TransmissionID   string          `json:"transmission_id,omitempty"`
    TransmissionSig  string          `json:"transmission_sig,omitempty"`
    TransmissionTime string          `json:"transmission_time,omitempty"`
    WebhookID        string          `json:"webhook_id,omitempty"`
    //Event            json.RawMessage `json:"webhook_event"`
    Event            json.RawMessage `json:"webhook_event,omitempty"`
}
```

PayPal will return a much clearer validation error indicating the body is empty, in this case:

```json
{"name":"VALIDATION_ERROR","message":"Invalid data provided","debug_id":"13DIalfanumer","information_link":"https://developer.paypal.com/docs/api/webhooks/#errors","details":[{"field":"webhook_event","location":"body","issue":"Required field cannot be blank"}],"links":[]}
```

Perhaps I could fork this in?

**Comment by plutov** [comment]
Thanks @madprogramer
