### ISSUE TITLE
add landing page to v2/checkout/orders

### ISSUE THREAD

**Issue by FedrBodr** [plutov/paypal#233]
In code i see commented ApplicationContext but now you can see at the documentation LandingPage https://developer.paypal.com/api/orders/v2/#definition-order_application_context

**Comment by ihipop** [comment]
I tested it and `application_context` is still usable,  but the doc reference is not correct in the code
they [reference to a V1 api doc](https://github.com/plutov/paypal/blob/4c16ffad0a4582b3cccb13acb8f7db85b0a66ed2/types.go#L195) but actually[ request a V2 endpoint](https://github.com/plutov/paypal/blob/4c16ffad0a4582b3cccb13acb8f7db85b0a66ed2/order.go#L27)
so `LandingPage` should also available but they commentd it out
