### ISSUE TITLE
POST https://api.sandbox.paypal.com/v2/checkout/orders: 401 Authentication failed due to invalid authentication credentials or a missing Authorization header.

### ISSUE THREAD

**Issue by gdlazcano** [plutov/paypal#245]
The order is being created as in the testing (because the docs are not updated) and returning 401 authentication failed when creating an order

```go
c, err := paypal.NewClient(
  clientId,
  secret,
  paypal.APIBaseSandBox,
)
if err != nil {
  panic(err)
}
// c.SetLog(os.Stdout)

ApplicationContext := &paypal.ApplicationContext{
  BrandName: "Imajo Broqueles",
  Locale:    "es-MX",
}

OrderPayer := &paypal.CreateOrderPayer{}

PurchaseUnit := paypal.PurchaseUnitRequest{
  Amount: &paypal.PurchaseUnitAmount{
    Currency: "MXN",
    Value:    "100.00",
    Breakdown: &paypal.PurchaseUnitAmountBreakdown{
      ItemTotal: &paypal.Money{Currency: "MXN", Value: "100.00"},
    },
  },
}

// Create a new order

paypalOrder, err := c.CreateOrder(
  context.Background(),
  paypal.OrderIntentCapture,
  []paypal.PurchaseUnitRequest{PurchaseUnit},
  OrderPayer,
  ApplicationContext,
)

if err != nil {
  fmt.Println(err)
  return
}
```

**Comment by gdlazcano** [comment]
![image](https://user-images.githubusercontent.com/49376133/187099566-6591972e-e564-45a8-a789-c58866a2d7f9.png)

I'm not sure if it's missing this Bearer authorization key

**Comment by MrWaggel** [comment]
Was having the same problem but I found the fix, you have to request an access token when you create a new client.

```
c, err := paypal.NewClient(...)
// err handle
_, err := c.GetAccessToken(context.Background())
// err handle

```

**Comment by milosrs** [comment]
Not that Access Token should get requested whenever you make a request to PayPal.
https://developer.paypal.com/docs/checkout/standard/integrate/

**Comment by deefdragon** [comment]
I feel like this is either a miss that the token is not fetched automatically on client creation, or a bug that calls to SendWithAuth wont create the token until its been manually created once (only updates the token if c.Token is not nil, client.go#L146)

**Comment by Hades32** [comment]
Agreed, this hit us too and I don't understand this API design decision. At seems it's related to the feature that you can manually set a token, but that seems more like an edge case (or maybe for testing) to me. Maybe @plutov can explain the rationale behind this

**Comment by roopakv** [comment]
I believe this is the way the client has been for a while and believe this is something we inherited, though I do agree that automatically requesting a token seems like good design. 

If someone wants to open a PR happy to help review it and get it through.
