### ISSUE TITLE
How can i verify payment?

### ISSUE THREAD

**Issue by shizzic** [plutov/paypal#246]
```golang
p, _ := paypal.NewClient("myClientId", "mySecret", paypal.APIBaseLive)
token, _ = p.GetAccessToken()
```
This code works just fine, in token var i got bearer token in key "access_token". And i have 17 length id that i got after made payment.
How can i get status or something of this payment with this code?

**Comment by shizzic** [comment]
"Payment" is checkout, so i was able to get it by curl with this GET /v2/checkout/orders/:id. But i don't understand hot to get my checout order by id with this repo.

**Comment by plutov** [comment]
How would you do it using Paypal REST API? This project is just a Go client, but you still have to understand how the API works.

**Comment by shizzic** [comment]
```
curl -v -X GET https://api.paypal.com/v2/checkout/orders/myorder17length\
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer someBearer"
```
Like this. I already retrieved this by curl as i said. But i just don't understand, how to perform it by this go client.
