### ISSUE TITLE
CHECKOUT.ORDER.COMPLETED response does not satisfty AnyEvent type

### ISSUE THREAD

**Issue by madprogramer** [plutov/paypal#252]
Yesterday I discovered that the response for CHECKOUT.ORDER.COMPLETED Includes a `zts` key. It raised an error when I attempted to decode it into [AnyEvent](https://github.com/plutov/paypal/blob/ebf596676edbc13c2ca46deb392735e079833e27/types.go#L1390).

```

// Decode JSON
var transaction paypal.AnyEvent

d := json.NewDecoder(bytes.NewReader(jsonBytes))
d.DisallowUnknownFields() // catch unwanted fields
err = d.Decode(&transaction)

if err != nil {
	//panic(err)
	log.Print(err)
	log.Print("\033[31m Received POST, unable to decode into JSON. See log.\033[0m");
	return
}

```

I have gone through the documentation page on [Orders](https://developer.paypal.com/docs/api/orders/v2/) and I have not been able to find anything on this `zts` whatsoever. But it is definitely there.

Here is a sample response [generated from the PayPal Webhook Simulator](https://developer.paypal.com/dashboard/webhooksSimulator)

```
{
  "id": "WH-COC11055RA711503B-4YM959094A144403T",
  "create_time": "2018-04-16T21:21:49.000Z",
  "resource_type": "checkout-order",
  "event_type": "CHECKOUT.ORDER.COMPLETED",
  "summary": "Checkout Order Completed",
  "resource": { ...  },
  "links": [ ... ],
  "event_version": "1.0",
  "zts": 1494957670, # <------------ This one here
  "resource_version": "2.0"
}
```

Any idea what this is, and how to typedef around it?

**Comment by plutov** [comment]
@madprogramer I didn't find a solution yet.

**Comment by madprogramer** [comment]
:clap:
