### ISSUE TITLE
Create Order error: paypal.Item.Tax is a String, API expects Object

### ISSUE THREAD

**Issue by graux** [plutov/paypal#256]
The Item struct has a Tax property as string:
```golang
	Item struct {
		Quantity    uint32 `json:"quantity"`
		Name        string `json:"name"`
		Price       string `json:"price"`
		Currency    string `json:"currency"`
		SKU         string `json:"sku,omitempty"`
		Description string `json:"description,omitempty"`
		Tax         string `json:"tax,omitempty"`
		UnitAmount  *Money `json:"unit_amount,omitempty"`
		Category    string `json:"category,omitempty"`
	}
```
The v2 orders docs say it should be an object (Money): https://developer.paypal.com/docs/api/orders/v2/#orders_create!path=purchase_units/items/tax&t=request

I guess it should be: (I have not tested it)
```golang
	Item struct {
		Quantity    uint32 `json:"quantity"`
		Name        string `json:"name"`
		Price       string `json:"price"`
		Currency    string `json:"currency"`
		SKU         string `json:"sku,omitempty"`
		Description string `json:"description,omitempty"`
		Tax         *Money `json:"tax,omitempty"`
		UnitAmount  *Money `json:"unit_amount,omitempty"`
		Category    string `json:"category,omitempty"`
	}
```

I am getting the following error when creating orders with items with + tax info:
- *Message:*`Request is not well-formed, syntactically incorrect, or violates schema.`
- *Details:*
  - *Field:* `/purchase_units/0/items/0/tax`
  - *Issue:* `MALFORMED_REQUEST_JSON`

**Comment by buffos** [comment]
Actually i made the same mistake. I imported  github.com/plutov/paypal and not github.com/plutov/paypal/v4
In that version it is fixed.

**Comment by buffos** [comment]
I think you can safely close the issue.

**Comment by graux** [comment]
Thank you @buffos
