### ISSUE TITLE
HTTP error would cause a "nil pointer dereference" runtime error

### ISSUE THREAD

**Issue by ochen** [plutov/paypal#26]
I found that the `Send` method of the `Client`, after doing a http request, would dump the http request and response before checking the error. Here's the code:

	resp, err = c.client.Do(req)
	c.log(req, resp)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

That will cause a "nil pointer dereference" if there is anything wrong with the http request (eg. an i/o timeout). Because in that case, the `resp` would be nil, making it impossible to get the body of `resp` in the `log` method.

**Comment by plutov** [comment]
Thanks, fixed in `log()` function
