### ISSUE TITLE
Subscriber struct contains outdated fields

### ISSUE THREAD

**Issue by Roolps** [plutov/paypal#260]
It appears as though the Paypal docs and the subscriber struct don't line up anymore. Am I allowed to amend this and PR?

https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create!path=subscriber&t=request
https://github.com/plutov/paypal/blob/master/types.go#L1255

**Comment by roopakv** [comment]
@Roolps for sure! Send us a PR and happy to help get it reviewed and updated
