### ISSUE TITLE
Create order body schema now uses payment_source

### ISSUE THREAD

**Issue by Roolps** [plutov/paypal#263]
https://developer.paypal.com/docs/api/orders/v2/#orders_create

Paypal has altered their  create order endpoint to take a payment_source object and has depracated the payer object.

https://developer.paypal.com/docs/api/orders/v2/#orders_create!path=payer&t=request
https://developer.paypal.com/docs/api/orders/v2/#orders_create!path=payment_source&t=request

**Comment by Roolps** [comment]
Ah turns out error was not because of this, but they indeed have udated their docs to use payment_source and deprecated payer. Should I leave this open?

**Comment by plutov** [comment]
@Roolps feel free to create a PR to make it up-to-date.

**Comment by Roolps** [comment]
Would you prefer if I remove the 'payer' parameter and replace this with payment source, or add the payment source as well as the payer?

https://github.com/plutov/paypal/blob/master/order.go#L28

I'll also add all of the payment sources listed in the docs that aren't already there
https://developer.paypal.com/docs/api/orders/v2/#orders_create!path=payment_source&t=request

**Comment by plutov** [comment]
@Roolps feel free to continue, we can keep both payer and payment source.
