### ISSUE TITLE
Add Functionality to Create Estimates

### ISSUE THREAD

**Issue by golang2go** [plutov/paypal#267]
### Add Functionality to Create Estimates

The library currently doesn't support creating estimates through the PayPal API. This feature is essential for businesses needing to send preliminary bills to clients. Adding this capability would enhance the library's usefulness, allowing developers to manage estimates programmatically in Go applications.

**Implementation Idea:**
- Implement functions for creating, retrieving, updating, and deleting estimates.
- Ensure compatibility with existing library structures and conventions.

Would love to get thoughts on this addition or if it's already in the works!

**Comment by plutov** [comment]
@golang2go what exact endpoint is that?
