### ISSUE TITLE
Subscriber struct error

### ISSUE THREAD

**Issue by 125ts** [plutov/paypal#268]
Subscriber struct {
		PayerID         string               `json:"payer_id"`
		ShippingAddress ShippingDetail       `json:"shipping_address,omitempty"`
		Name            CreateOrderPayerName `json:"name,omitempty"`
		EmailAddress    string               `json:"email_address,omitempty"`
	}
 cause some error，if not define ShippingAddress
should change to
Subscriber struct {
		PayerID         string               `json:"payer_id"`
		ShippingAddress *ShippingDetail       `json:"shipping_address,omitempty"`
		Name            *CreateOrderPayerName `json:"name,omitempty"`
		EmailAddress    string               `json:"email_address,omitempty"`
	}

**Comment by plutov** [comment]
@gaoxunyang can you please make a PR?

Best,
https://packagemain.tech/

**Comment by 125ts** [comment]
done

**Comment by 125ts** [comment]
Why wasn't it merged in?
