### ISSUE TITLE
AuthorizeOrderResponse uses invalid []PurchaseUnitRequest as PurchaseUnits.

### ISSUE THREAD

**Issue by jenszahner** [plutov/paypal#271]
https://github.com/plutov/paypal/blob/3713084b64e9c7c20291706b85730871aeb0da65/types.go#L493 
The type AuthorizeOrderResponse used PurchaseUnitRequest in the response, but this is not correct according to the Paypal documentation linked below. Paypal differs between PurchaseUnit (1) and PurchaseUnitRequest (2).

(1) https://developer.paypal.com/docs/api/orders/v2/#definition-purchase_unit
(2) https://developer.paypal.com/docs/api/orders/v2/#definition-purchase_unit_request

**Comment by plutov** [comment]
Thanks, fixed in v4.10.1
