### ISSUE TITLE
CreateSinglePayout: Synchronous mode will soon be deprecated and is no longer available for new integrations

### ISSUE THREAD

**Issue by angelacastanieto** [plutov/paypal#31]
I'm now getting this message back from the Paypal sandbox when I call the CreateSinglePayout function:

`Synchronous mode will soon be deprecated and is no longer available for new integrations. You can use the asynchronous mode by specifying sync_mode= false in the request.`

**Comment by plutov** [comment]
@angelacastanieto can you please create a PR as you already have a fix in fork repo for this problem?
