### ISSUE TITLE
ErrorResponse.Details not parsed

### ISSUE THREAD

**Issue by nd2s** [plutov/paypal#40]
The field is always empty. 

`ErrorResponse.Detail` has type `string` but API returns string array. client.go:110 does no error checking.

Example response from PayPal:

```
{"name":"VALIDATION_ERROR","debug_id":"xxx","message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/","details":[{"field":"name","issue":"A profile with this name already exists"}]}
```

**Comment by plutov** [comment]
Thanks @nd2s will look into it today!

**Comment by plutov** [comment]
@nd2s please check, updated master
