### ISSUE TITLE
Doesn't work for Indian merchants !!!!

### ISSUE THREAD

**Issue by ghost** [plutov/paypal#52]
Works fine in dev mode, shows "Return to merchant" in production mode, it is similar to following issue : 

https://github.com/braintree/braintree-android-drop-in/issues/53

```
c.CreateDirectPaypalPayment
```

Works and creates a redirect link.

After redirect link is opened it shows "Return to merchant" , sometimes shows "Unsupported payee currency" in production mode.

I wasted like 7 months to get this to work :( 

Because I'm a solo developer I thought there must be some error on my end.
So I ended up changing implementation of Paypal SDK more than 3 times in my golang project.

After trying hard enough, I got this to work by using a buy now button with IPN listener by using some hacks such as passing user ID in custom field etc.

I got ill and was ICU for few weeks to get this to work in less time.

I followed suggestions that were given in `github.com/logpacker/PayPal-Go-SDK`, It worked fine in dev mode but as soon as I switched to production mode it didn't work.

As a result I had implement one more payment option (Instamojo) which took more time to get the actual product ready. 

I had no issues with Instamojo even though they do not provide a package for golang, they even provide option to specify webhook URL for payment notifications.

I feel so bad right now, I don't even know what suggestion to give to make this to work without any issues for Indian merchants, but still here is a list that I have made that may ease the process.

- If please make SDKs fail in dev mode itself so we will know that it will not work in production.

**Comment by plutov** [comment]
I think it's not related to SDK, but to PayPal platform restrictions. I don't have any background to fix this.
