### ISSUE TITLE
Add examples to handle errors in documentation

### ISSUE THREAD

**Issue by emigr2k1** [plutov/paypal#65]
Sometimes paypal returns errors like: 

> 400 Invalid request - see details

And we have to type assert the error to get the details field but currently, in README.md there's no examples of error handling.

**Comment by plutov** [comment]
Hi @emigr2k1,
Can you please share the example of code and how you do type assert? Maybe we need to change how errors are returned. Thank you!

**Comment by emigr2k1** [comment]
Hi, @plutov.
I'm sorry I didn't reply before. I didn't get the notification.
I was testing the library when I posted this issue and I don't have the code anymore.
The error I got was coming from:
```go
func (c *Client) ExecuteApprovedPayment(paymentID string, payerID string) (*ExecuteResponse, error){...}
```
in payment.go but maybe this happens in other methods aswell
As you can see this function returns a normal error interface. To have access to the fields we have to use:
```go
err.(*paypalsdk.ErrorResponse).Details
```

**Comment by plutov** [comment]
Hi @emigr2k1 are you able to provide a PR to solve this? But please keep error return value to be compatible.

**Comment by emigr2k1** [comment]
I could but [this](https://blog.golang.org/error-handling-and-go) and [this](https://golang.org/doc/faq#nil_error) recommend to return a normal error instead of a custom error and then use type assert.
So, probably the best way to solve this is just to add a section in the documentation showing how to handle the returned errors to get access to the ErrorResponse struct fields.
I'll provide a PR with examples handling errors if you think it's ok. Or maybe edit the example_test.go file and change:
```go
if err != nil {
    panic(err)
}
```
To something like:
```go
if err != nil {
    errDetails := err.(*ErrorResponse).Details
    panic(errDetails)
}
```

**Comment by plutov** [comment]
Or maybe we should format an `error` with correct description using Details inside the package, so panic(err) will be easy to understand.

**Comment by emigr2k1** [comment]
Yes. I think that's better.

**Comment by archana-iron** [comment]
I am facing the same error, why this error occured?
I am not able to find the solution

**Comment by archana-iron** [comment]
Also need to confirm one more thing, the credit card details we are adding here are of which account? I mean   of some other customer, or merchant of app itself?
Thanks in advance!

**Comment by emigr2k1** [comment]
@archana-iron, try printing the error with:
```go
err.(*paypalsdk.ErrorResponse).Details
```
About the credit card, it is the credit card of the payer but if I recall correctly, you can't use credit card method for payments. Try using
```go
PaymentMethod: "paypal",
```
In the Payer field of a payment.
Check the official docs of paypal for more info. And you should create a new issue.
