### ISSUE TITLE
Incorrect Item Quantity data type

### ISSUE THREAD

**Issue by Mido-sys** [plutov/paypal#66]
Hello, 

According to  Paypal docs, the quantity item should be a string https://developer.paypal.com/docs/api/payments/v1/#definition-item and not int https://github.com/logpacker/PayPal-Go-SDK/blob/master/types.go#L291
as shown here.

Please check this ticket for more info:

https://github.com/paypal/PayPal-REST-API-issues/issues/272

**Comment by plutov** [comment]
https://github.com/logpacker/PayPal-Go-SDK/pull/68
