### ISSUE TITLE
Sandbox payment amount is not displayed

### ISSUE THREAD

**Issue by Cheney-Su** [plutov/paypal#72]
Hello, I have a question about the amount shown?

` clientId := "AehUCWtgSv0ZXi-4o8P9jQ8oeyP07NRw0UqVzCwFFStmzq5-OqEXMhJGLr7HBqqbt9UonFHtHln4NVMC"
	secretId := "EH2PBwQU5sGxFxaEjYiT8QuO7Ejs74QYkOAmQZRQ1kJMYFOauB7enxGSlxd5l9aUKKFVVO_73aVV1QLs"
	c, err := paypalsdk.NewClient(clientId, secretId, paypalsdk.APIBaseSandBox)
	if err != nil {
		fmt.Println("paypalsdk.NewClient err", err.Error())
	}
	accessToken, err := c.GetAccessToken()
	if err != nil {
		fmt.Println("c.GetAccessToken err", err.Error())
	}
	fmt.Println(accessToken.Token)

	amount := paypalsdk.Amount{
		Total:    "100.00",
		Currency: "USD",
	}
	redirectURI := "http://www.baidu.com"
	cancelURI := "http://www.baidu.com"
	description := "maimaimai"
	paymentResult, err := c.CreateDirectPaypalPayment(amount, redirectURI, cancelURI, description)
	fmt.Println(paymentResult.Links)`

I got a link from paymentResult，However, the payment amount of the page is not displayed.
Can you tell me how to solve it?Thanks！

**Comment by plutov** [comment]
Seems like currently this client doesn't support it. I will add it soon following https://developer.paypal.com/docs/api/payments/v1/

**Comment by plutov** [comment]
Added fix to tag v1.1.4
