### ISSUE TITLE
How do I generate a client token?

### ISSUE THREAD

**Issue by kerhael** [plutov/paypal#74]
Hi,

To be able to display our app's info, our client needs to query Paypal with a client token.

Paypal documentation says that:

> Your server is responsible for generating a client token, which contains the authorization and configuration details that your client needs to initialize the client SDK.

We tried the following:
```
paypalClient, _ := paypalsdk.NewClient(clientID, secretID, url)
token, _ := paypalClient.GetAccessToken()
```
But the generated token does not seem to be destined to be used client side.

How can I use you library to generate a client token? Is it even possible? We did not find the endpoint we need to call in Paypal documentation.

Thanks in advance,

Best regards

**Comment by plutov** [comment]
Hi,

Not sure if standard PayPal SDK supports it, I believe you took it from Braintree SDK - https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/

So seems like a server with Braintree SDK should generate it.

**Comment by kerhael** [comment]
Hi,

Indeed after more digging we realized that I had planned using standard PayPal SDK server side but our client cannot use standard PayPal SDK (it needs to work on TVs too, where no browser is available)...

It seems that I am going to have to use a braintree library.

Not an issue for you anyway :).

Thanks for the quick answer!
