### ISSUE TITLE
is there a plan support the api Version 2?

### ISSUE THREAD

**Issue by YouEclipse** [plutov/paypal#76]
thanks for your paypal sdk for go!
paypal has upgraded some api (Payments/Orders)  to Version 2 and  recommend to upgrade to Version 2;
![image](https://user-images.githubusercontent.com/8252317/53413909-6202a280-3a08-11e9-8be8-ac36b66a8ad9.png)
Is there a plan to support Version 2?

**Comment by plutov** [comment]
Yes, I am planning to create V2 support in the same repo and user can select which version to use. I will use this ticket to show the progress.

Docs - https://developer.paypal.com/docs/api/payments/v2/

**Comment by Fyb3roptik** [comment]
Any update on this?

**Comment by plutov** [comment]
I am still not sure how to support both versions in same project, PayPal v2 is incompatible with v1, so all structs, endpoints have to be changed, some have to be removed and new have to be added.

I am planning to have 2 separate folders inside the project: v1 and v2 and change the imports to `github.com/logpacker/PayPal-Go-SDK/v1`.

**Comment by Fyb3roptik** [comment]
V1 is deprecated, just please do V2 and do not support multiple versions. If someone wants V1, they can use an older version of this library

**Comment by Fyb3roptik** [comment]
Tag a V1 release, then move on to V2

**Comment by Fyb3roptik** [comment]
Just saw it is end of life on Sunday. No need to ever support V1 anymore then, since they wont even support it.

**Comment by plutov** [comment]
Update:
Tags v1.\*.\* contain PayPal V2 version
Tag **v2.0.0** contains PayPal V2 version
