### ISSUE TITLE
Cancel Billing Agreement

### ISSUE THREAD

**Issue by dominhtri1995** [plutov/paypal#78]
Hi,

I'm new here. Trying to write the Cancel Billing Agreement method using SendWithAuth. I keep getting error "500 An internal service error occured". Below is my code:

`req, err := PaypalClient.NewRequest("POST", fmt.Sprintf("%s%s", PaypalClient.APIBase, "/v1/payments/billing-agreements/"+user.PaypalBillingId+"/cancel"), nil)`

`var response interface{} `
`err = PaypalClient.SendWithAuth(req, response)`

Also what should I do with the response 204 no content ? It looks like the interface{} is causing problem as well.
However if I use curl in the terminal, everything is fine

**Comment by plutov** [comment]
Will close it, since it will be changed in v2.
