### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by dominhtri1995** [plutov/paypal#79]
When cycles_remaining of an Infinite Billing Agreement too big. Unmarshal into AgreementDetails.cycles_remaining will fail.

Error: cannot unmarshal number 18446744073709551615 into Go struct field AgreementDetails.cycles_remaining of type int64

**Comment by plutov** [comment]
Hi @dominhtri1995 thanks for the info, will check how to unmarshal it correctly.

**Comment by plutov** [comment]
Will close it, since it will be changed in v2.
