### ISSUE TITLE
new subscriptions API support?

### ISSUE THREAD

**Issue by szczk** [plutov/paypal#81]
Hi there,
PayPal subscription API will be deprecated as of March 31, 2019.
It seems like some endpoints will be changed, and billing plans and agreements are going away.
I assume you plan to upgrade the library sooner or later to adjust to the new api, 
but how far up the priorities list is this? :smile:  
Will the new api replace the old one, or be added alongside it?

**Comment by plutov** [comment]
Thanks for the update. Since this project uses semver, it will make sense to release a major version in the same project.

**Comment by plutov** [comment]
Will close it, since it will be changed in v2.
