### ISSUE TITLE
Pay with Vaulted Card

### ISSUE THREAD

**Issue by Fyb3roptik** [plutov/paypal#85]
In V2 how do we pay with a vaulted card once it is stored? I cannot for the life of me get it to work! It keeps giving me ORDER_NOT_APPROVED

**Comment by Fyb3roptik** [comment]
Ok I was adding token info into the Create Order. When I remove it, I now get a 500 error when doing a Capture

**Comment by Fyb3roptik** [comment]
Ok after speaking with Paypal, apparently Vaulted cards for V2 isnt out yet and we have to use the V1 endpoint for this. Can you make the necessary update for this? Or should I do a PR?

**Comment by Fyb3roptik** [comment]
@plutov

**Comment by plutov** [comment]
Hi @Fyb3roptik it would be nice if you can do a PR for this.

**Comment by carvendy** [comment]
I have same problem

**Comment by carvendy** [comment]
`req, err := c.NewRequest("POST", fmt.Sprintf("%s%s", c.APIBase, "/v2/checkout/orders/"+orderID+"/capture"), nil)
	if err != nil {
	 	return capture, err
	}

	if err = c.SendWithAuth(req, capture); err != nil {
		capture, err
	}`

after change this code , this is work.
`":"https://api.sandbox.paypal.com/v2/checkout/orders/9HJ48641AL856994W","rel":"up","method":"GET"}],"create_time":"2019-07-21T01:13:09Z","update_time":"2019-07-21T01:13:09Z"}]}}],"payer":{"name":{"given_name":"x","surname":"x"},"email_address":"xxxxxxxx","payer_id":"xxxxxxxxxxx","address":{"country_code":"C2"}},"links":[{"href":"https://api.sandbox.paypal.com/v2/checkout/orders/9HJ48641AL856994W","rel":"self","method":"GET"}],"status":"COMPLETED"`

**Comment by Fyb3roptik** [comment]
Sorry I got pulled off of this after PayPal wouldn't let us do vaulted cards
