### ISSUE TITLE
Get country iso code for a payment in v2

### ISSUE THREAD

**Issue by lindroth** [plutov/paypal#88]
In version v1 you could get the country iso code from a payment like this:
```
payment, err := c.client.GetPayment("PayPalPaymentID")
  if err != nil {
    return err	
  }

code :=  payment.Payer.PayerInfo.CountryCode
```
How can I get the country code for the payer of a payment in v2?

**Comment by plutov** [comment]
In V2 I don't see how can I get payment by ID, do you know if it's even possible? https://developer.paypal.com/docs/api/payments/v2/

**Comment by lindroth** [comment]
@plutov , so far I have found no way.
