### ISSUE TITLE
CaptureOrder function doesn't meet current spec

### ISSUE THREAD

**Issue by TheArmando** [plutov/paypal#89]
I'm having issues integrating with PayPal's Checkout API, either I'm looking at the wrong docs or PayPal has made API changes recently. 

[captureOrder](https://developer.paypal.com/docs/api/orders/v2/#orders_capture) requires a different payload than required by the SDK. A "payment_source" consisting of a token and card object compared to an amount and currency object.

I'm seeing a similar issue with [authorizeOrder](https://developer.paypal.com/docs/api/orders/v2/#orders_authorize)

There also appears to be a missing method called [updateOrder](https://developer.paypal.com/docs/api/orders/v2/#orders_patch)

Any help would be appreciated!

**Comment by plutov** [comment]
I started to work on this - https://github.com/logpacker/PayPal-Go-SDK/pull/90
