### ISSUE TITLE
what is authID?

### ISSUE THREAD

**Issue by carvendy** [plutov/paypal#94]
give me a hand

**Comment by elvis-hp** [comment]
yes, i need too!

**Comment by carvendy** [comment]
get token
`
c, err := paypalsdk.NewClient(clientID, secret,url)
	c.SetLog(os.Stdout) 
	accessToken, err := c.GetAccessToken()
`

create order

`
payPayOrder, err := c.CreateOrder(paypalsdk.OrderIntentCapture, []paypalsdk.PurchaseUnitRequest{
					paypalsdk.PurchaseUnitRequest{
						Description: order.OrderNo, 
						Amount: aa}},
					&paypalsdk.PayerInfo{},
					&paypalsdk.ApplicationContext{})
`

pay callback

`req, err := cc.NewRequest("POST",fmt.Sprintf("%s%s",cc.APIBase,"/v2/checkout/orders/"+payResult.PayId+"/capture"), nil)
			if err = cc.SendWithAuth(req, capture); err != nil {

				return
			}

`
